apiVersion: v1
kind: Service

metadata:
  name: personalbrand-website-service

spec:
  type: NodePort

  selector:
    app: personalbrand-website

  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30090
